---
name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: task_db
          MYSQL_ROOT_PASSWORD: Ayodeji@312
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -pAyodeji@312"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest pytest-django mysqlclient

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -hmysql -uroot -pAyodeji@312 --silent; do
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: Run migrations
        env:
          DB_ENGINE: django.db.backends.mysql
          DB_NAME: task_db
          DB_USER: root
          DB_PASSWORD: Ayodeji@312
          DB_HOST: mysql
          DB_PORT: 3306
          DJANGO_SETTINGS_MODULE: config.settings
          DJANGO_SECRET_KEY: dummy
        run: |
          python manage.py migrate

      - name: Run linting
        run: |
          flake8 .

      - name: Run tests
        env:
          DB_ENGINE: django.db.backends.mysql
          DB_NAME: task_db
          DB_USER: r_
